[package]
name = "ad_lsp"
version = "0.1.0"
edition = "2021"

[dependencies]
lsp-types = "0.97.0"
serde = "1.0.215"
serde_json = "1.0.133"
tracing = "0.1.40"
tracing-subscriber = { version = "0.3.18", features = [ "fmt" ] }
